using System.Collections.Generic;
using System.Linq;

namespace EngineRoom.Generators.Helpers
{
    /// <summary>
    /// Composes a final generated .cs file from a type-body template fragment.
    /// Prepends the auto-generated header and wraps the body in a block-scoped
    /// namespace (via the shared Namespace template) when one is supplied.
    /// File-scoped namespaces are intentionally avoided because Unity's default
    /// language version doesn't accept them.
    /// </summary>
    internal static class SourceFileBuilder
    {
        private const string FileHeader = "// <auto-generated/>\n#nullable enable\n\n";
        private const string NamespaceIndent = "    ";

        public static string Build(string typeBody, string? containingNamespace)
        {
            var body = containingNamespace is null
                ? typeBody
                : WrapInNamespace(typeBody, containingNamespace);

            return FileHeader + body;
        }

        private static string WrapInNamespace(string content, string containingNamespace)
        {
            var indented = string.Join("\n", content.Split('\n').Select(IndentNonEmpty));

            return TemplateLoader.LoadAndSubstitute("Namespace", new Dictionary<string, string>
            {
                ["Namespace"] = containingNamespace,
                ["Content"] = indented,
            });
        }

        // Whitespace-only lines (e.g. a templated placeholder line that became empty
        // after substitution) get collapsed to a true empty line so the generated
        // output doesn't carry trailing-whitespace noise.
        private static string IndentNonEmpty(string line)
        {
            var trimmed = line.TrimEnd();
            return trimmed.Length == 0 ? string.Empty : NamespaceIndent + trimmed;
        }
    }
}
